### ISSUE TITLE
Suggestion: have script check if dependencies are already installed on termux before downloading them

### ISSUE THREAD

**Issue by Areahints** [Rajkumrdusad/IP-Tracer#3]

**Comment by Rajkumrdusad** [comment]
Sorry ?

**Comment by Areahints** [comment]
The application downloads libraries like perl, php, python etc, I'm suggesting that the script should check first if they are installed and then skip them, as compared to downloading them then asking to overwrite

**Comment by Rajkumrdusad** [comment]
Ok got it. this is a proper way to install dependent libraries.
